name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore
    - name: Test
      run: dotnet test GeekBurguer.Products.UnitTests/GeekBurguer.Products.UnitTests.csproj
    - name: Publish
      run: |
        dotnet publish --no-restore -o ./out /p:Version=2.0.${{ github.run_number }}
    - name: Pack
      run: |
        dotnet pack --no-restore -o ./nupkgs /p:Version=2.0.${{ github.run_number }}  
